######################################################################
<<<<<<< HEAD
# Automatically generated by qmake (2.01a) Sat Oct 26 00:36:49 2013
=======
# Automatically generated by qmake (2.01a) Thu Oct 24 21:02:39 2013
>>>>>>> 8ac407f79f0f5f4c2189ac8119662efa7d6c931d
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
